RENDER_TYPE: ANGULAR_UNIVERSAL

TEMPLATE:
  INDEX: "./dist/index.html"
  CATEGORY_LIST: "./dist/index.html"
  CATEGORY: "./dist/index.html"
  ARTICLE: "./dist/index.html"

INDEX_TYPE: one

INDEX_ARTICLE_NUMBER: 7

ALL_PAGE_ARTICLE_NUMBER: 20

PAGING_START_N: 1

LANG: "zh-CN"

TEXT:
  FOOTER: "陳放為的博客 All rights reserved."
  AUTHOR: "陳放為"
  AUTHOR_DESC: "一个码农"

LINK:
  GITHUB: "https://github.com/AbyChan/"

IMG:
  FOOTER_AVATOR: '/static/img/me.jpg'
